### ISSUE TITLE
nasm: command not found: ft_isalnum.s

### ISSUE THREAD

**Issue by eraleis** [ncoden/libft#2]
``` shell
→ make
make: nasm: Command not foundheck/ft_isalnum.s
make: *** [obj/basics/chars/check/ft_isalnum.o] Error 127
```

**Comment by ncoden** [comment]
This lib doesn't use dependency management tool.
You have to install **[nasm](http://www.nasm.us/)**, an assembly compiler.

You can **download the last version 2.11.09 [here](http://www.nasm.us/pub/nasm/releasebuilds/2.11.09rc1/)** and **[install it](https://theintobooks.wordpress.com/2012/11/01/installing-nasm/)**
_Linux, OSX and Windows, but the libft isn't compatible with this last one_

Or **download and install it from shell**:
- Linux & cie

```
sudo apt-get install nasm
```
- Mac OSX (with [Homebrew](http://brew.sh/))

```
sudo brew install nasm
```
